# MetaItems
# Goals
goal_smb1_part = "Final Bowser (SMB1)"
goal_smb1_true = "True Final Bowser (SMB1)"
goal_smbll_part = "Final Bowser (SMBLL)"
goal_smbll_true = "True Final Bowser (SMBLL)"
goal_smb1 = "SMB1 Goal"
goal_smbll = "SMBLL Goal"
goal_smb2 = "SMB2 Goal"
goal_smb3 = "SMB3 Goal"
goal_smw = "SMW Goal"
goal_smasw = "Complete SMASW"
# Boss Coins
bosscoin_smb1 = "Boss Coin (SMB1)"
bosscoin_smbll = "Boss Coin (SMBLL)"
bosscoin_smb2 = "Boss Coin (SMB2)"
bosscoin_smb3 = "Boss Coin (SMB3)"
bosscoin_smw = "Boss Coin (SMW)"

# World Keys

# SMB1
key_world_1_smb1 = "World 1 Key (SMB1)"
key_world_2_smb1 = "World 2 Key (SMB1)"
key_world_3_smb1 = "World 3 Key (SMB1)"
key_world_4_smb1 = "World 4 Key (SMB1)"
key_world_5_smb1 = "World 5 Key (SMB1)"
key_world_6_smb1 = "World 6 Key (SMB1)"
key_world_7_smb1 = "World 7 Key (SMB1)"
key_world_8_smb1 = "World 8 Key (SMB1)"
key_world_x1_smb1 = "World X1 Key (SMB1)"
key_world_x2_smb1 = "World X2 Key (SMB1)"
key_world_x3_smb1 = "World X3 Key (SMB1)"
key_world_x4_smb1 = "World X4 Key (SMB1)"
key_world_x5_smb1 = "World X5 Key (SMB1)"
key_world_x6_smb1 = "World X6 Key (SMB1)"
key_world_x7_smb1 = "World X7 Key (SMB1)"
key_world_x8_smb1 = "World X8 Key (SMB1)"
key_world_minus = "Minus World Key (SMB1)"
key_prog_smb1 = "Progressive Key (SMB1)"

# SMBLL
key_world_1_smbll = "World 1 Key (SMBLL)"
key_world_2_smbll = "World 2 Key (SMBLL)"
key_world_3_smbll = "World 3 Key (SMBLL)"
key_world_4_smbll = "World 4 Key (SMBLL)"
key_world_5_smbll = "World 5 Key (SMBLL)"
key_world_6_smbll = "World 6 Key (SMBLL)"
key_world_7_smbll = "World 7 Key (SMBLL)"
key_world_8_smbll = "World 8 Key (SMBLL)"
key_world_fantasy = "Fantasy World Key (SMBLL)"
key_world_a_smbll = "World A Key (SMBLL)"
key_world_b_smbll = "World B Key (SMBLL)"
key_world_c_smbll = "World C Key (SMBLL)"
key_world_d_smbll = "World D Key (SMBLL)"
key_prog_smbll = "Progressive Key (SMBLL)"

# SMB1+SMBLL CrossCombo
key_prog_crosscombo = "Progressive Key (SMBP)"

# SMB2
key_world_1_smb2 = "World 1 Key (SMB2)"
key_world_2_smb2 = "World 2 Key (SMB2)"
key_world_3_smb2 = "World 3 Key (SMB2)"
key_world_4_smb2 = "World 4 Key (SMB2)"
key_world_5_smb2 = "World 5 Key (SMB2)"
key_world_6_smb2 = "World 6 Key (SMB2)"
key_world_7_smb2 = "World 7 Key (SMB2)"
key_prog_smb2 = "Progressive Key (SMB2)"

# SMB3
key_world_1_smb3 = "World 1 Key (SMB3)"
key_world_2_smb3 = "World 2 Key (SMB3)"
key_world_3_smb3 = "World 3 Key (SMB3)"
key_world_4_smb3 = "World 4 Key (SMB3)"
key_world_5_smb3 = "World 5 Key (SMB3)"
key_world_6_smb3 = "World 6 Key (SMB3)"
key_world_7_smb3 = "World 7 Key (SMB3)"
key_world_8_smb3 = "World 8 Key (SMB3)"
key_prog_smb3 = "Progressive Key (SMB3)"

# SMW (Doesn't use keys, but does use game unlock
key_game_smw = "Game Unlock (SMW)"

# Auxiliary Important Unlocks

# SMB2
unlock_char_mario = "Mario Unlock (SMB2)"
unlock_char_luigi = "Luigi Unlock (SMB2)"
unlock_char_peach = "Peach Unlock (SMB2)"
unlock_char_toad = "Toad Unlock (SMB2)"

# SMW
unlock_switch_yellow = "Yellow Switch Unlock (SMW)"
unlock_switch_green = "Green Switch Unlock (SMW)"
unlock_switch_red = "Red Switch Unlock (SMW)"
unlock_switch_blue = "Blue Switch Unlock (SMW)"
unlock_autumn_koopa = "Special Zone Koopa Recolors (SMW)"

# Egghunt
egghunt_smb1 = "Yoshi Egg (SMB1)"
egghunt_smbll = "Yoshi Egg (SMBLL)"
egghunt_smb2 = "Yoshi Egg (SMB2)"
egghunt_smb3 = "Yoshi Egg (SMB3)"
egghunt_smw = "Yoshi Egg (SMW)"

# Abilities
ability_dash_smb1 = "Dash (SMB1)"
ability_dash_smbll = "Dash (SMBLL)"
ability_dash_smb2 = "Dash (SMB2)"
ability_dash_smb3 = "Dash (SMB3)"
ability_dash_smw = "Dash (SMW)"
ability_climb_smb1 = "Climb (SMB1)"
ability_climb_smbll = "Climb (SMBLL)"
ability_climb_smb2 = "Climb (SMB2)"
ability_climb_smb3 = "Climb (SMB3)"
ability_climb_smw = "Climb (SMW)"
ability_swim_smb1 = "Swim (SMB1)"
ability_swim_smbll = "Swim (SMBLL)"
ability_swim_smb3 = "Swim (SMB3)"
ability_swim_smw = "Swim (SMW)"
ability_carry_smb2 = "Grab (SMB2)"
ability_carry_smb3 = "Grab (SMB3)"
ability_carry_smw = "Grab (SMW)"
ability_starman_smb1 = "Starman (SMB1)"
ability_starman_smbll = "Starman (SMBLL)"
ability_starman_smb2 = "Starman (SMB2)"
ability_starman_smb3 = "Starman (SMB3)"
ability_starman_smw = "Starman (SMW)"
ability_pswitch_smb2 = "Clock (SMB2)" # It technically functions like one.
ability_pswitch_smb3 = "P-Switch (SMB3)"
ability_pswitch_smw = "P-Switch (SMW)"
ability_mount_smb3 = "Kuribo Shoe (SMB3)"
ability_mount_smw = "Yoshi (SMW)"
ability_special_smb2 = "Potion (SMB2)"
ability_special_smw = "Spinjump (SMW)"

# Power-Ups
powerup_mushroom_smb1 = "Super Mushroom State (SMB1)"
powerup_mushroom_smbll = "Super Mushroom State (SMBLL)"
powerup_mushroom_smb3 = "Super Mushroom State (SMB3)"
powerup_mushroom_smw = "Super Mushroom State (SMW)"
powerup_flower_smb1 = "Fire Flower State (SMB1)"
powerup_flower_smbll = "Fire Flower State (SMBLL)"
powerup_flower_smb3 = "Fire Flower State (SMB3)"
powerup_flower_smw = "Fire Flower State (SMW)"
powerup_leaf = "Super Leaf State (SMB3)"
powerup_frog = "Frog Suit State (SMB3)"
powerup_hammer = "Hammer Suit State (SMB3)"
powerup_tanuki = "Tanooki Suit State (SMB3)"
powerup_infinifly = "P-Wing State (SMB3)"
powerup_balloon = "P-Balloon State (SMW)"
powerup_feather = "Cape Feather State (SMW)"
powerup_prog_smb1 = "Progressive Power-Up (SMB1)"
powerup_prog_smbll = "Progressive Power-Up (SMBLL)"
powerup_prog_smw = "Progressive Power-Up (SMW)"
powerup_prog_health_1 = "Progressive World 1 Health (SMB2)"
powerup_prog_health_2 = "Progressive World 2 Health (SMB2)"
powerup_prog_health_3 = "Progressive World 3 Health (SMB2)"
powerup_prog_health_4 = "Progressive World 4 Health (SMB2)"
powerup_prog_health_5 = "Progressive World 5 Health (SMB2)"
powerup_prog_health_6 = "Progressive World 6 Health (SMB2)"
powerup_prog_health_7 = "Progressive World 7 Health (SMB2)"
powerup_prog_health_a = "Progressive Health (SMB2)"

# Filler
filler_coin_single_smb1 = "1 Coin (SMB1)"
filler_coin_single_smbll = "1 Coin (SMBLL)"
filler_coin_single_smb2 = "1 Coin (SMB2)"
filler_coin_single_smb3 = "1 Coin (SMB3)"
filler_coin_single_smw = "1 Coin (SMW)"
filler_coin_five_smb1 = "5 Coins (SMB1)"
filler_coin_five_smbll = "5 Coins (SMBLL)"
filler_coin_five_smb2 = "5 Coins (SMB2)"
filler_coin_five_smb3 = "5 Coins (SMB3)"
filler_coin_five_smw = "5 Coins (SMW)"
filler_coin_ten_smb1 = "10 Coins (SMB1)"
filler_coin_ten_smbll = "10 Coins (SMBLL)"
filler_coin_ten_smb2 = "10 Coins (SMB2)"
filler_coin_ten_smb3 = "10 Coins (SMB3)"
filler_coin_ten_smw = "10 Coins (SMW)"
filler_coin_huge_smb1 = "50 Coins (SMB1)"
filler_coin_huge_smbll = "50 Coins (SMBLL)"
filler_coin_huge_smb2 = "15 Coins (SMB2)"
filler_coin_huge_smb3 = "50 Coins (SMB3)"
filler_coin_huge_smw = "50 Coins (SMW)"
filler_mini_star_smb1 = "Mini Starman (SMB1)"
filler_mini_star_smbll = "Mini Starman (SMBLL)"
filler_mini_star_smb2 = "Mini Starman (SMB2)"
filler_mini_star_smb3 = "Mini Starman (SMB3)"
filler_mini_star_smw = "Mini Starman (SMW)"
filler_mini_powerup_smb1 = "Pocket Mushroom (SMB1)"
filler_mini_powerup_smbll = "Pocket Mushroom (SMBLL)"
filler_mini_powerup_smb2 = "Pocket Heart (SMB2)"
filler_mini_powerup_smb3 = "Pocket Mushroom (SMB3)"
filler_mini_powerup_smw = "Pocket Mushroom (SMW)"
filler_extra_life_smb1 = "1-UP (SMB1)"
filler_extra_life_smbll = "1-UP (SMBLL)"
filler_extra_life_smb2 = "1-UP (SMB2)"
filler_extra_life_smb3 = "1-UP (SMB3)"
filler_extra_life_smw = "1-UP (SMW)"